services:
  helios:
    build: .
    image: "docker.io/ptrusr/roflios@sha256:bdc41eb1634e2464f35b8cc09bd92d72ad57b3d04137ea8b345fd1cbb6fb6608"
    platform: linux/amd64
    ports:
      - "1337:1337"                             # Expose Helios RPC port
    annotations:
      net.oasis.proxy.ports.1337.custom_domain: ethrpc.rofl.cloud
    volumes:
      - helios-data:/root/.helios               # Persistent Helios data storage.
      - /run/rofl-appd.sock:/run/rofl-appd.sock # appd REST API.
    environment:
      - INFURA_API_KEY=${INFURA_API_KEY}

volumes:
  helios-data:
